stages:
- name: Publish apache service image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: reg.406.csie.nuu.edu.tw
    env:
      PLUGIN_BUILD_ARGS: --progress=tty --network=host
      PLUGIN_DEBUG: "true"
      PLUGIN_MIRROR: https://mirror.gcr.io
- name: deploy apps
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:bitnami-apache
      version: 7.3.14
      answers:
        image.pullSecrets[0]: harbor-local
        image.registry: reg.406.csie.nuu.edu.tw
        image.repository: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}
        image.tag: ${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
        service.type: NodePort
      name: web
      targetNamespace: apache-cert-template
notification: {}
